spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/orders?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: "root"
    password: "123456"
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:
    properties:
       hibernate:
    show-sql: true
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error